export const PAKISTAN_GEO = [
  {
    name: 'Punjab',
    districts: [
      { name: 'Lahore', cities: ['Lahore', 'Raiwind', 'Shahdara'] },
      { name: 'Faisalabad', cities: ['Faisalabad', 'Jaranwala', 'Samundri', 'Tandlianwala'] },
      { name: 'Rawalpindi', cities: ['Rawalpindi', 'Murree', 'Gujar Khan', 'Kahuta'] },
      { name: 'Gujranwala', cities: ['Gujranwala', 'Hafizabad', 'Wazirabad', 'Kamoke'] },
      { name: 'Multan', cities: ['Multan', 'Shujabad', 'Jalalpur Pirwala'] },
      { name: 'Sialkot', cities: ['Sialkot', 'Daska', 'Sambrial', 'Pasrur'] },
      { name: 'Bahawalpur', cities: ['Bahawalpur', 'Bahawalnagar', 'Rahim Yar Khan'] },
      { name: 'Sargodha', cities: ['Sargodha', 'Bhalwal', 'Kot Momin', 'Shahpur'] },
      { name: 'Sheikhupura', cities: ['Sheikhupura', 'Nankana Sahib', 'Muridke'] },
      { name: 'Jhang', cities: ['Jhang', 'Chiniot', 'Shorkot'] },
      { name: 'Okara', cities: ['Okara', 'Renala Khurd', 'Depalpur'] },
      { name: 'Kasur', cities: ['Kasur', 'Chunian', 'Pattoki'] },
      { name: 'Gujrat', cities: ['Gujrat', 'Kharian', 'Sarai Alamgir'] },
      { name: 'Sahiwal', cities: ['Sahiwal', 'Chichawatni', 'Pakpattan'] },
      { name: 'Dera Ghazi Khan', cities: ['Dera Ghazi Khan', 'Rajanpur', 'Layyah'] },
      { name: 'Vehari', cities: ['Vehari', 'Mailsi', 'Burewala'] },
      { name: 'Muzaffargarh', cities: ['Muzaffargarh', 'Kot Addu', 'Alipur'] },
      { name: 'Mianwali', cities: ['Mianwali', 'Esa Khel', 'Piplan'] },
      { name: 'Attock', cities: ['Attock', 'Hazro', 'Fateh Jang'] },
      { name: 'Chakwal', cities: ['Chakwal', 'Choa Saidan Shah', 'Talagang'] },
      { name: 'Jhelum', cities: ['Jhelum', 'Sohawa', 'Pind Dadan Khan'] },
      { name: 'Khushab', cities: ['Khushab', 'Joharabad', 'Noorpur'] },
      { name: 'Narowal', cities: ['Narowal', 'Shakargarh', 'Zafarwal'] },
      { name: 'Toba Tek Singh', cities: ['Toba Tek Singh', 'Gojra', 'Kamalia'] },
      { name: 'Nankana Sahib', cities: ['Nankana Sahib'] },
      { name: 'Chiniot', cities: ['Chiniot'] },
      { name: 'Hafizabad', cities: ['Hafizabad', 'Pindi Bhattian'] },
    ],
  },
  {
    name: 'Sindh',
    districts: [
      { name: 'Karachi', cities: ['Karachi', 'Korangi', 'Malir', 'Gadap', 'Bin Qasim'] },
      { name: 'Hyderabad', cities: ['Hyderabad', 'Latifabad', 'Qasimabad'] },
      { name: 'Sukkur', cities: ['Sukkur', 'Rohri', 'Salehpat'] },
      { name: 'Larkana', cities: ['Larkana', 'Dokri', 'Ratodero'] },
      { name: 'Nawabshah', cities: ['Nawabshah', 'Sakrand', 'Moro'] },
      { name: 'Mirpur Khas', cities: ['Mirpur Khas', 'Umerkot', 'Digri'] },
      { name: 'Thatta', cities: ['Thatta', 'Sujawal', 'Gharo'] },
      { name: 'Badin', cities: ['Badin', 'Talhar', 'Matli'] },
      { name: 'Dadu', cities: ['Dadu', 'Mehar', 'Johi'] },
      { name: 'Jacobabad', cities: ['Jacobabad', 'Thul', 'Garhi Khairo'] },
      { name: 'Shikarpur', cities: ['Shikarpur', 'Lakhi', 'Garhi Yasin'] },
      { name: 'Khairpur', cities: ['Khairpur', 'Kingri', 'Gambat'] },
      { name: 'Sanghar', cities: ['Sanghar', 'Shahdadpur', 'Tando Adam'] },
      { name: 'Tharparkar', cities: ['Mithi', 'Islamkot', 'Chachro'] },
      { name: 'Ghotki', cities: ['Ghotki', 'Daharki', 'Mirpur Mathelo'] },
    ],
  },
  {
    name: 'Khyber Pakhtunkhwa',
    districts: [
      { name: 'Peshawar', cities: ['Peshawar', 'Hayatabad', 'Charsadda Road'] },
      { name: 'Mardan', cities: ['Mardan', 'Rustam', 'Katlang'] },
      { name: 'Swat', cities: ['Saidu Sharif', 'Mingora', 'Matta', 'Bahrain'] },
      { name: 'Abbottabad', cities: ['Abbottabad', 'Havelian', 'Mansehra'] },
      { name: 'Kohat', cities: ['Kohat', 'Hangu', 'Lachi'] },
      { name: 'Bannu', cities: ['Bannu', 'Domel', 'Lakki Marwat'] },
      { name: 'Dera Ismail Khan', cities: ['Dera Ismail Khan', 'Paharpur', 'Tank'] },
      { name: 'Nowshera', cities: ['Nowshera', 'Pabbi', 'Jehangira'] },
      { name: 'Charsadda', cities: ['Charsadda', 'Tangi', 'Shabqadar'] },
      { name: 'Haripur', cities: ['Haripur', 'Ghazi', 'Havelian'] },
      { name: 'Swabi', cities: ['Swabi', 'Topi', 'Razzar'] },
      { name: 'Buner', cities: ['Daggar', 'Totalai', 'Gagra'] },
      { name: 'Dir Lower', cities: ['Timergara', 'Samar Bagh', 'Munda'] },
      { name: 'Dir Upper', cities: ['Chitral', 'Drosh', 'Mirkhani'] },
    ],
  },
  {
    name: 'Balochistan',
    districts: [
      { name: 'Quetta', cities: ['Quetta', 'Sariab', 'Samungli'] },
      { name: 'Gwadar', cities: ['Gwadar', 'Pasni', 'Ormara'] },
      { name: 'Turbat', cities: ['Turbat', 'Mand', 'Buleda'] },
      { name: 'Khuzdar', cities: ['Khuzdar', 'Zehri', 'Naal'] },
      { name: 'Hub', cities: ['Hub', 'Uthal', 'Bela'] },
      { name: 'Zhob', cities: ['Zhob', 'Sherani', 'Muslim Bagh'] },
      { name: 'Loralai', cities: ['Loralai', 'Barkhan', 'Duki'] },
      { name: 'Chaman', cities: ['Chaman', 'Qila Abdullah', 'Spin Boldak'] },
      { name: 'Kalat', cities: ['Kalat', 'Mangochar', 'Surab'] },
      { name: 'Sibi', cities: ['Sibi', 'Lehri', 'Harnai'] },
      { name: 'Nasirabad', cities: ['Dera Murad Jamali', 'Tamboo', 'Chattar'] },
      { name: 'Lasbela', cities: ['Uthal', 'Bela', 'Winder'] },
    ],
  },
  {
    name: 'Azad Jammu & Kashmir',
    districts: [
      { name: 'Muzaffarabad', cities: ['Muzaffarabad', 'Garhi Dupatta', 'Chakothi'] },
      { name: 'Mirpur', cities: ['Mirpur', 'Dadyal', 'Chakswari'] },
      { name: 'Rawalakot', cities: ['Rawalakot', 'Bagh', 'Hajira'] },
      { name: 'Kotli', cities: ['Kotli', 'Sehnsa', 'Charhoi'] },
      { name: 'Bhimber', cities: ['Bhimber', 'Samahni', 'Barnala'] },
      { name: 'Neelum', cities: ['Athmuqam', 'Sharda', 'Keran'] },
    ],
  },
  {
    name: 'Gilgit-Baltistan',
    districts: [
      { name: 'Gilgit', cities: ['Gilgit', 'Jutial', 'Danyore'] },
      { name: 'Skardu', cities: ['Skardu', 'Shigar', 'Khaplu'] },
      { name: 'Hunza', cities: ['Karimabad', 'Aliabad', 'Ganesh'] },
      { name: 'Ghanche', cities: ['Khaplu', 'Saltoro', 'Mashkel'] },
      { name: 'Diamer', cities: ['Chilas', 'Darel', 'Tangir'] },
      { name: 'Astore', cities: ['Astore', 'Rama', 'Gurez'] },
    ],
  },
  {
    name: 'Islamabad Capital Territory',
    districts: [
      { name: 'Islamabad', cities: ['Islamabad', 'Rawat', 'Kahuta', 'Tarnol'] },
    ],
  },
];
